name: Build

on: [ "push", "pull_request" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.14'
      - uses: actions/checkout@master
      - run: go get -v -t -d
      - run: go build
      - run: go test -v -covermode=count -coverprofile=coverage.out ./...
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          GO111MODULE=off go get github.com/mattn/goveralls
          $(go env GOPATH)/bin/goveralls -coverprofile=coverage.out -service=github
        working-directory: src/github.com/wenbenz/sago