name: Build

on: [ "push", "pull_request" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.14'
      - uses: actions/checkout@master
      - run: go get -v -t -d
      - run: go build

      # Coverage
      - run: mkdir -p $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/src/github.com/wenbenz/sago
      - run: cp -r ./ $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/src/github.com/wenbenz/sago
      - run: go get github.com/mattn/goveralls && go install github.com/mattn/goveralls
      - name: Coveralls test
        run: |
          cd $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/src/github.com/wenbenz/sago
          go test -v -covermode=count -coverprofile=coverage.out ./...
          $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -coverprofile=coverage.out -service=github -repotoken ${{ secrets.GITHUB_TOKEN }}