name: Go Report Card

on:
  push:
    branches: [ master ]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gofmt
        run: gofmt -w -s .
      - name: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -a -m "GitHub Action: gofmt" || true
      - name: push
        run: |
          git remote set-url origin https://${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push --set-upstream origin $(git branch --show-current)

  reportcard:
    name: Report Card
    needs: Format
    runs-on: ubuntu-latest
    steps:
    - name: Go report card
      uses: creekorful/goreportcard-action@v1.0