name: Go Report Card

#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

on: [ "push", "pull_request" ]

jobs:
  format:
    name: Format
    continue-on-error: true # if already formatted, gofmt will fail
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gofmt
        run: gofmt -w -s .
      - name: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -a -m "GitHub Action: gofmt"
      - name: push
        env:
          branch: $(git rev-parse --abbrev-ref HEAD)
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: {{ env.branch }}


  reportcard:
    name: Report Card
    needs: Format
    runs-on: ubuntu-latest
    steps:
    - name: Go report card
      uses: creekorful/goreportcard-action@v1.0